.\" $OpenBSD: at.1,v 1.52 2014/09/16 15:56:36 jmc Exp $
.\"
.\" Copyright (C) 1993, 1994  Thomas Koenig
.\" Copyright (C) 1993  David Parsons
.\" Copyright (C) 2002  Todd C. Miller
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. The name of the author(s) may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR(S) ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: September 16 2014 $
.Dt AT 1
.Os
.Sh NAME
.Nm at ,
.Nm batch
.Nd queue, examine or delete jobs for later execution
.Sh SYNOPSIS
.Nm at
.Op Fl f Ar file
.Op Fl l
.Fl t Ar time_arg
.Nm at
.Fl r
.Ar job ...
.Nm batch
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm at
and
.Nm batch
read commands from standard input or a specified file which
are to be executed at a later time.
.Bl -tag -width Ds
.It Nm at
Executes commands at a specified time.
.It Nm batch
Executes commands when system load levels permit.
.El
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl f Ar file
Read the job from
.Ar file
rather than standard input.
.It Fl l
Display the queue of jobs which are currently awaiting execution.
.It Fl r Ar job ...
Remove the specified job(s) from the
.Nm at
queue.
.It Fl t Ar time_arg
Specify the job time.
The argument should be of the form
.Oo Oo Ar cc Oc Ns Ar yy Oc Ns Ar mmddHHMM Ns Op \&. Ns Ar SS ,
where the parts of the argument represent the following:
.Pp
.Bl -tag -width Ds -compact -offset indent
.It Ar ccyy
Year.
If yy is specified, but cc is not,
a value for yy between 69 and 99 results in a cc value of 19.
Otherwise, a cc value of 20 is used.
.It Ar mm
Month:
a number from 1 to 12.
.It Ar dd
Day:
a number from 1 to 31.
.It Ar HH
Hour:
a number from 0 to 23.
.It Ar MM
Minute:
a number from 0 to 59.
.It Ar SS
Second:
a number from 0 to 60
(permitting a leap second),
preceded by a period.
The default is 0.
.El
.Pp
This is the same as the time format used by
.Xr touch 1 .
.El
.Sh FILES
.Bl -tag -width /var/cron/at.allow -compact
.It Pa /var/cron/atjobs
directory containing job files
.El
.Sh EXIT STATUS
The
.Nm
utility exits with one of the following values:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It 0
Jobs were successfully submitted, removed, or listed.
.It >0
An error occurred.
.El
.Sh EXAMPLES
Run a job at 10:25am on July 31:
.Pp
.Dl $ at -f file -t 07311025
.Sh SEE ALSO
.Xr atq 1 ,
.Xr atrm 1 ,
.Xr sh 1 ,
.Xr touch 1 ,
.Xr cron 8
