.\"	$OpenBSD: find.1,v 1.90 2015/02/28 21:51:56 bentley Exp $
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	from: @(#)find.1	8.1 (Berkeley) 6/6/93
.\"
.Dd $Mdocdate: February 28 2015 $
.Dt FIND 1
.Os
.Sh NAME
.Nm find
.Nd walk a file hierarchy
.Sh SYNOPSIS
.Nm find
.Ar path ...\&
.Op Ar expression
.Sh DESCRIPTION
.Nm
recursively descends the directory tree for each
.Ar path
listed, evaluating an
.Ar expression
(composed of the
.Dq primaries
and
.Dq operators
listed below) in terms
of each file in the tree.
In the absence of an expression,
.Ic -print
is assumed.
If an expression is given,
but none of the primaries
.Ic -exec ,
.Ic -print ,
or
.Ic -print0
are specified, the given expression is effectively replaced by
.Cm \&( Ar given expression Cm \&)
.Ic -print .
.Sh PRIMARIES
.Bl -tag -width Ds -compact
.It Ic -exec Ar utility Oo Ar argument ... Oc \&;
Execute the specified
.Ar utility .
Optional arguments may be passed to the utility.
The
.Ar utility
is executed once per path.
If the string
.Qq {}
appears anywhere in the utility name or the arguments
it is replaced by the pathname of the current file.
The expression must be terminated by a semicolon
.Pq Ql \&; .
.Pp
.It Ic -iname Ar pattern
Identical to the
.Ic -name
primary except that the matching is done in a case insensitive manner.
.Pp
.It Ic -name Ar pattern
True if the last component of the pathname being examined matches
.Ar pattern ,
which may use any of the special characters documented in
.Xr glob 7 .
.Pp
.It Ic -newer Ar file
True if the current file has a more recent last modification time than
.Ar file .
.Pp
.It Ic -path Ar pattern
True if the pathname being examined matches
.Ar pattern ,
which may use any of the special characters documented in
.Xr glob 7 .
Slashes
.Pq Ql /
are treated as normal characters and do not have to be
matched explicitly.
.Pp
.It Ic -print
This primary always evaluates to true.
It prints the pathname of the current file to standard output, followed
by a newline
.Pq Ql \en
character.
.Pp
.It Ic -print0
This primary always evaluates to true.
It prints the pathname of the current file to standard output, followed
by a null character, suitable for use with the
.Fl 0
option to
.Xr xargs 1 .
.Pp
.It Ic -prune
This primary always evaluates to true.
It causes
.Nm
to not descend into the current file.
.Pp
.It Ic -type Ar t
True if the file is of the specified type.
Possible file types are as follows:
.Pp
.Bl -tag -width flag -offset indent -compact
.It Cm b
block special
.It Cm c
character special
.It Cm d
directory
.It Cm f
regular file
.It Cm l
symbolic link
.It Cm p
FIFO
.It Cm s
socket
.El
.El
.Sh OPERATORS
The primaries may be combined using the following operators.
The operators are listed in order of decreasing precedence.
.Pp
.Bl -tag -width "(expression)" -compact
.It Cm \&( Ar expression Cm \&)
This evaluates to true if the parenthesized expression evaluates to
true.
.Pp
.It Cm \&! Ar expression
This is the unary
.Tn NOT
operator.
It evaluates to true if the expression is false.
.Pp
.It Ar expression Cm -a Ar expression
.It Ar expression expression
The logical AND operator.
As it is implied by the juxtaposition of two expressions it does not
have to be specified.
The expression evaluates to true if both expressions are true.
The second expression is not evaluated if the first expression is false.
.Pp
.It Ar expression Cm -o Ar expression
The logical OR operator.
The expression evaluates to true if either the first or the second expression
is true.
The second expression is not evaluated if the first expression is true.
.El
.Pp
Operators, primaries, and arguments to primaries must be separate
arguments to
.Nm find ,
i.e. they should be separated by whitespace.
.Sh EXIT STATUS
The
.Nm
utility exits with a value of 0 on successful traversal of all path operands
or with a value >0 if an error occurred.
.Sh EXAMPLES
Print out a list of all the files whose names end in
.Dq \&.c :
.Pp
.Dl "$ find / -name '*.c'"
.Pp
Find all files in
.Pa /usr/src
ending in a dot and single digit, but skip directory
.Pa /usr/src/gnu :
.Pp
.Dl "$ find /usr/src -path /usr/src/gnu -prune -o -name \e*.[0-9]"
.Pp
Find and remove all *.jpg and *.gif files under the current working
directory:
.Pp
.Dl "$ find . \e( -name \e*.jpg -o -name \e*.gif \e) -exec rm {} \e;"
or
.Dl "$ find . \e( -name \e*.jpg -o -name \e*.gif \e) -print0 | xargs -0r rm"
.Sh SEE ALSO
.Xr chflags 1 ,
.Xr chmod 1 ,
.Xr locate 1 ,
.Xr ls 1 ,
.Xr whereis 1 ,
.Xr which 1 ,
.Xr xargs 1 ,
.Xr stat 2 ,
.Xr fts 3 ,
.Xr glob 7 ,
.Xr symlink 7
.Sh HISTORY
A
.Nm
command appeared in
.At v1 .
.Sh CAVEATS
The special characters used by
.Nm
are also special characters to many shell programs.
In particular, the characters
.Ql * ,
.Ql \&[ ,
.Ql \&] ,
.Ql \&? ,
.Ql \&( ,
.Ql \&) ,
.Ql \&! ,
.Ql \e ,
and
.Ql \&;
may have to be escaped from the shell.
