.\"	$OpenBSD: grep.1,v 1.43 2015/01/13 04:45:34 daniel Exp $
.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)grep.1	8.3 (Berkeley) 4/18/94
.\"
.Dd $Mdocdate: January 13 2015 $
.Dt GREP 1
.Os
.Sh NAME
.Nm grep , egrep , fgrep ,
.Nd file pattern searcher
.Sh SYNOPSIS
.Nm grep
.Bk -words
.Op Fl cilnqRsvx
.Op Fl e Ar pattern
.Op Fl f Ar file
.Op Ar pattern
.Op Ar
.Ek
.Sh DESCRIPTION
The
.Nm grep
utility searches any given input files,
selecting lines that match one or more patterns.
Patterns may consist of one or more lines,
allowing any of the pattern lines to match a portion of the input.
Each input line that matches at least one of the patterns is written
to the standard output.
If no file arguments are specified, the standard input is used.
.Pp
The related programs are as follows:
.Bl -tag -width indent
.It Nm grep
Simple patterns and basic regular expressions
.Pq BREs .
.It Nm egrep
Extended regular expressions
.Pq EREs .
.It Nm fgrep
Fixed patterns only
(i.e. no regular expressions).
.El
.Pp
See
.Xr re_format 7
for more information on regular expressions.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl c
Only a count of selected lines is written to standard output.
.It Fl e Ar pattern
Specify a pattern used during the search of the input.
An input line is selected if it matches any of the specified patterns.
.It Fl f Ar file
Read one or more newline separated patterns from
.Ar file .
Empty pattern lines match every input line.
Newlines are not considered part of a pattern.
If
.Ar file
is empty, nothing is matched.
.It Fl i
Perform case insensitive matching.
By default,
.Nm grep
is case sensitive.
.It Fl l
Only the names of files containing selected lines are written to
standard output.
.Nm grep
will only search a file until a match has been found,
making searches potentially less expensive.
Pathnames are listed once per file searched.
If the standard input is searched, the string
.Dq (standard input)
is written.
.It Fl n
Each output line is preceded by its relative line number in the file,
starting at line 1.
The line number counter is reset for each file processed.
This option is ignored if
.Fl c ,
.Fl l ,
or
.Fl q
is
specified.
.It Fl q
Quiet mode.
Suppress normal output.
.It Fl R
Recursively search subdirectories listed.
.It Fl s
Silent mode.
Nonexistent and unreadable files are ignored
(i.e. their error messages are suppressed).
.It Fl v
Selected lines are those
.Em not
matching any of the specified patterns.
.It Fl x
Only input lines selected against an entire fixed string or regular
expression are considered to be matching lines.
.El
.Sh EXIT STATUS
The
.Nm grep
utility exits with one of the following values:
.Pp
.Bl -tag -width indent -compact
.It Li 0
One or more lines were selected.
.It Li 1
No lines were selected.
.It Li \*(Gt1
An error occurred.
.El
.Sh EXAMPLES
Find all occurrences of the word
.Sq foo
in
.Sq myfile :
.Pp
.Dl $ grep 'foo' myfile
.Pp
Find all occurrences of the pattern
.Ql .Pp
at the beginning of a line:
.Pp
.Dl $ grep '^\e.Pp' myfile
.Pp
Find all lines in a file which do not contain the words
.Sq foo
or
.Sq bar :
.Pp
.Dl $ grep -v -e 'foo' -e 'bar' myfile
.Pp
Find all occurrences of 19, 20, or 25 in the file
.Sq calendar :
.Pp
.Dl $ egrep '19|20|25' calendar
.Sh SEE ALSO
.Xr ed 1 ,
.Xr ex 1 ,
.Xr sed 1 ,
.Xr re_format 7
.Sh HISTORY
The
.Nm grep
command first appeared in
.At v4 .
