.\"	$OpenBSD: hier.7,v 1.137 2014/11/17 18:19:08 deraadt Exp $
.\"	$NetBSD: hier.7,v 1.7 1994/11/30 19:07:10 jtc Exp $
.\"
.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)hier.7	8.1 (Berkeley) 6/5/93
.\"
.Dd $Mdocdate: November 17 2014 $
.Dt HIER 7
.Os
.Sh NAME
.Nm hier
.Nd layout of filesystems
.Sh DESCRIPTION
A sketch of the filesystem hierarchy.
.Bl -tag -width "/home/"
.It /
Root directory.
.It /bin/
User utilities fundamental to both single and multi-user environments.
These programs are statically compiled and therefore do not depend on any
system libraries to run.
.It /dev/
Block and character device files.
.It /etc/
System configuration files and scripts.
.It /home/
Default location for user home directories.
.It /mnt/
Empty directory commonly used by
system administrators as a temporary mount point.
.It /root/
Default home directory for the superuser.
.It /sbin/
System programs and administration utilities
fundamental to both single and multi-user environments.
These programs are statically compiled and therefore do not depend on any
system libraries to run.
.It /tmp/
Temporary files that are
.Em not
preserved between system reboots.
Periodically cleaned by
.Xr daily 8 .
.It /usr/
Contains the majority of user utilities and applications.
.Bl -tag -width "include/X"
.It X11R6/
Files required for the X11 window system.
.It bin/
Common utilities, programming tools, and applications.
.It games/
Useful and semi-frivolous programs.
.It include/
Standard C include files.
.It lib/
System libraries.
.It libdata/
Miscellaneous utility data files.
.It libexec/
System daemons and utilities (executed by other programs).
.It local/
Local executables, libraries, etc.
.It sbin/
System daemons and utilities (executed by users).
.It share/
Architecture independent data files.
.El
.It /var/
Multi-purpose log, temporary, transient, and spool files.
.El
.Sh SEE ALSO
.Xr apropos 1 ,
.Xr find 1 ,
.Xr locate 1 ,
.Xr whatis 1 ,
.Xr whereis 1 ,
.Xr which 1
.Sh HISTORY
A
.Nm
manual appeared in
.At v7 .
