.\"  $OpenBSD: od.1,v 1.30 2014/04/19 09:24:28 sobrado Exp $
.\"  $NetBSD: od.1,v 1.16 2001/12/07 01:23:42 bjh21 Exp $
.\"
.\" Copyright (c) 2001 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Andrew Brown.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"/
.Dd $Mdocdate: April 19 2014 $
.Dt OD 1
.Os
.Sh NAME
.Nm od
.Nd octal, decimal, hexadecimal, ascii dump
.Sh SYNOPSIS
.Nm od
.Op Fl bcdosv
.Op Fl A Ar base
.Op Fl j Ar offset
.Op Fl N Ar length
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility sequentially copies the input from each specified file,
or the standard input if no files are specified,
to the standard output,
transforming the data according to the options given.
.Pp
If no options are specified,
the default display is equivalent to specifying the
.Fl o
option.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A Ar base
Specify the input address base.
The argument
.Ar base
may be one of
.Cm o ,
.Cm d ,
.Cm x ,
or
.Cm n ,
which specify octal, decimal, hexadecimal
addresses or no address, respectively.
.It Fl b
.Em One-byte octal display .
Display the input offset in octal, followed by sixteen
space-separated, three column, zero-filled, bytes of input data, in
octal, per line.
This is the default output style if no other is selected.
.It Fl c
.Em One-byte character display .
Display the input offset in octal, followed by sixteen
space-separated, three column, space-filled, characters of input data,
per line.
Control characters are printed as
.Sq C
style escapes, or as three octal digits,
if no
.Sq C
escape exists for the character.
.It Fl d
.Em Two-byte unsigned decimal display .
Display the input offset in octal, followed by eight
space-separated, five column, zero-filled, two-byte units
of input data, in unsigned decimal, per line.
.It Fl h
.Em Two-byte hexadecimal display .
Display the input offset in octal, followed by eight space-separated,
four column, zero filled, two-byte units of input data, in hexadecimal,
per line.
.It Fl j Ar offset
Skip
.Ar offset
bytes from the beginning of the input.
By default,
.Ar offset
is interpreted as a decimal number.
With a leading
.Cm 0x
or
.Cm 0X ,
.Ar offset
is interpreted as a hexadecimal number,
otherwise, with a leading
.Cm 0 ,
.Ar offset
is interpreted as an octal number.
Appending the character
.Cm b ,
.Cm k ,
or
.Cm m
to
.Ar offset
causes it to be interpreted as a multiple of
.Li 512 ,
.Li 1024 ,
or
.Li 1048576 ,
respectively.
.It Fl N Ar length
Interpret only
.Ar length
bytes of input.
.Ar length
is interpreted as a decimal number.
.It Fl o
.Em Two-byte octal display .
Display the input offset in octal, followed by eight
space-separated, six column, zero-filled, two-byte units
of input data, in octal, per line.
.It Fl s
.Em Two-byte signed decimal display .
Display the input offset in octal, followed by eight
space-separated, five column, zero-filled, two-byte units
of input data, in signed decimal, per line.
.It Fl v
The
.Fl v
option causes
.Nm
to display all input data.
Without the
.Fl v
option, any number of groups of output lines, which would be
identical to the immediately preceding group of output lines (except
for the input offsets), are replaced with a line comprised of a
single asterisk
.Pq Ql \&* .
.El
.Sh EXIT STATUS
.Ex -std od
.Sh EXAMPLES
Display two-byte hexadecimal output, but skip the first 16 bytes:
.Pp
.Dl $ od -hv -j 16 file
.Sh SEE ALSO
.Xr hexdump 1 ,
.Xr ascii 7
.Sh HISTORY
An
.Nm
command appeared in
.At v1 .
